services:
  app:
    container_name: tcr-world-tour-php
    build:
        context: ./docker/php
        args:
            UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005
    volumes:
      - ./:/app
      - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
        - tcr-network

  webserver:
    container_name: tcr-world-tour-nginx
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - "8000:80"
    volumes:
      - ./public:/appdata/www/public
    networks:
        - tcr-network

  db:
    container_name: tcr-world-tour-mysql
    build:
        context: ./docker/database
    ports:
      - "10000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db
    volumes:
      - symfony-data:/var/lib/mysql
    networks:
        - tcr-network
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redis:
    container_name: tcr-world-tour-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      tcr-network:
        aliases:
          - redis

  rabbitmq:
    container_name: tcr-world-tour-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      tcr-network:
        aliases:
          - rabbitmq

volumes:
  symfony-data:

networks:
  tcr-network:
