controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_test:
    path: /user/test
    controller: App\Controller\UserController::test

user_get:
    path: /user/get
    controller: App\Controller\UserController::getUsers

user_create:
    path: /user/create
    controller: App\Controller\UserController::createUser

racers_get:
    path: v1/racers
    controller: App\Controller\RacerController::getRacers
    methods: ['GET']

product_create:
    path: product
    controller: App\Controller\ProductController::createProduct
    methods: ['GET']

product_get:
    path: get/product
    controller: App\Controller\ProductController::getProducts
    methods: ['GET']
