controllers:
    resource:
        path: ../src/infrastructure/controller/
        namespace: App\infrastructure\controller
    type: attribute

user_test:
    path: /user/test
    controller: App\infrastructure\controller\UserController::test

user_get:
    path: /user/get
    controller: App\infrastructure\controller\UserController::getUsers

user_create:
    path: /user/create
    controller: App\infrastructure\controller\UserController::createUser

racers_get:
    path: v1/racers
    controller: App\infrastructure\controller\RacerController::getRacers
    methods: ['GET']

product_create:
    path: product
    controller: App\infrastructure\controller\ProductController::createProduct
    methods: ['GET']

product_get:
    path: get/product
    controller: App\infrastructure\controller\ProductController::getProducts
    methods: ['GET']

driver_get:
    path: v1/driver
    controller: App\infrastructure\controller\DriverController::getDrivers
    methods: ['GET']

team_get:
    path: v1/team
    controller: App\infrastructure\controller\TeamController::getTeams
    methods: ['GET']
